// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BrowserService fetches web pages and returns cleaned HTML for display.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * ClearCache clears the page cache.
 */
export function ClearCache(): $CancellablePromise<void> {
    return $Call.ByID(826779980);
}

/**
 * FetchPage fetches a URL and returns cleaned HTML suitable for rendering.
 * Scripts are removed, relative URLs are made absolute, and basic styling is preserved.
 */
export function FetchPage(rawURL: string): $CancellablePromise<string> {
    return $Call.ByID(1796371612, rawURL);
}
