// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigService exposes configuration to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetConfig returns the full configuration.
 */
export function GetConfig(): $CancellablePromise<$models.Config> {
    return $Call.ByID(2320765359).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetConfigPath returns the path to the config file so the user can edit it.
 */
export function GetConfigPath(): $CancellablePromise<string> {
    return $Call.ByID(2174556168);
}

/**
 * ReloadConfig re-reads the config file from disk.
 */
export function ReloadConfig(): $CancellablePromise<$models.Config> {
    return $Call.ByID(1474954900).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.Config.createFrom;
