// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Bookmark {
    "name": string;
    "url": string;

    /** Creates a new Bookmark instance. */
    constructor($$source: Partial<Bookmark> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Bookmark instance from a string or object.
     */
    static createFrom($$source: any = {}): Bookmark {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Bookmark($$parsedSource as Partial<Bookmark>);
    }
}

export class BrowserConfig {
    "homepage": string;
    "bookmarks": Bookmark[];

    /** Creates a new BrowserConfig instance. */
    constructor($$source: Partial<BrowserConfig> = {}) {
        if (!("homepage" in $$source)) {
            this["homepage"] = "";
        }
        if (!("bookmarks" in $$source)) {
            this["bookmarks"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BrowserConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): BrowserConfig {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("bookmarks" in $$parsedSource) {
            $$parsedSource["bookmarks"] = $$createField1_0($$parsedSource["bookmarks"]);
        }
        return new BrowserConfig($$parsedSource as Partial<BrowserConfig>);
    }
}

/**
 * Config holds all user-configurable settings for Workspacer.
 */
export class Config {
    "ui": UIConfig;
    "terminal": TerminalConfig;
    "browser": BrowserConfig;
    "panes": PanesConfig;

    /** Creates a new Config instance. */
    constructor($$source: Partial<Config> = {}) {
        if (!("ui" in $$source)) {
            this["ui"] = (new UIConfig());
        }
        if (!("terminal" in $$source)) {
            this["terminal"] = (new TerminalConfig());
        }
        if (!("browser" in $$source)) {
            this["browser"] = (new BrowserConfig());
        }
        if (!("panes" in $$source)) {
            this["panes"] = (new PanesConfig());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     */
    static createFrom($$source: any = {}): Config {
        const $$createField0_0 = $$createType2;
        const $$createField1_0 = $$createType3;
        const $$createField2_0 = $$createType4;
        const $$createField3_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ui" in $$parsedSource) {
            $$parsedSource["ui"] = $$createField0_0($$parsedSource["ui"]);
        }
        if ("terminal" in $$parsedSource) {
            $$parsedSource["terminal"] = $$createField1_0($$parsedSource["terminal"]);
        }
        if ("browser" in $$parsedSource) {
            $$parsedSource["browser"] = $$createField2_0($$parsedSource["browser"]);
        }
        if ("panes" in $$parsedSource) {
            $$parsedSource["panes"] = $$createField3_0($$parsedSource["panes"]);
        }
        return new Config($$parsedSource as Partial<Config>);
    }
}

/**
 * PaneConfig describes the configuration for a single pane in the workspace layout.
 */
export class PaneConfig {
    /**
     * ID is a unique identifier for the pane.
     */
    "id": string;

    /**
     * Type is the kind of pane: "terminal", "browser", "notes", or "agent".
     */
    "type": string;

    /**
     * Title is the display title for the pane tab/header.
     */
    "title": string;

    /**
     * Width is the default width of the pane in pixels.
     */
    "width": number;

    /**
     * Order determines the left-to-right position of the pane.
     */
    "order": number;

    /** Creates a new PaneConfig instance. */
    constructor($$source: Partial<PaneConfig> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("order" in $$source)) {
            this["order"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PaneConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): PaneConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PaneConfig($$parsedSource as Partial<PaneConfig>);
    }
}

export class PanesConfig {
    "defaultWidth": number;
    "gap": number;
    "peek": number;
    "insertPosition": string;
    "default": PaneConfig[];

    /** Creates a new PanesConfig instance. */
    constructor($$source: Partial<PanesConfig> = {}) {
        if (!("defaultWidth" in $$source)) {
            this["defaultWidth"] = 0;
        }
        if (!("gap" in $$source)) {
            this["gap"] = 0;
        }
        if (!("peek" in $$source)) {
            this["peek"] = 0;
        }
        if (!("insertPosition" in $$source)) {
            this["insertPosition"] = "";
        }
        if (!("default" in $$source)) {
            this["default"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PanesConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): PanesConfig {
        const $$createField4_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("default" in $$parsedSource) {
            $$parsedSource["default"] = $$createField4_0($$parsedSource["default"]);
        }
        return new PanesConfig($$parsedSource as Partial<PanesConfig>);
    }
}

export class ShellOption {
    "name": string;
    "path": string;
    "label": string;

    /** Creates a new ShellOption instance. */
    constructor($$source: Partial<ShellOption> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ShellOption instance from a string or object.
     */
    static createFrom($$source: any = {}): ShellOption {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ShellOption($$parsedSource as Partial<ShellOption>);
    }
}

export class TerminalConfig {
    "shell": string;
    "shells": ShellOption[];
    "fontFamily": string;
    "fontSize": number;
    "scrollback": number;
    "cursorBlink": boolean;
    "cursorStyle": string;

    /** Creates a new TerminalConfig instance. */
    constructor($$source: Partial<TerminalConfig> = {}) {
        if (!("shell" in $$source)) {
            this["shell"] = "";
        }
        if (!("shells" in $$source)) {
            this["shells"] = [];
        }
        if (!("fontFamily" in $$source)) {
            this["fontFamily"] = "";
        }
        if (!("fontSize" in $$source)) {
            this["fontSize"] = 0;
        }
        if (!("scrollback" in $$source)) {
            this["scrollback"] = 0;
        }
        if (!("cursorBlink" in $$source)) {
            this["cursorBlink"] = false;
        }
        if (!("cursorStyle" in $$source)) {
            this["cursorStyle"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): TerminalConfig {
        const $$createField1_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("shells" in $$parsedSource) {
            $$parsedSource["shells"] = $$createField1_0($$parsedSource["shells"]);
        }
        return new TerminalConfig($$parsedSource as Partial<TerminalConfig>);
    }
}

export class UIConfig {
    "animations": boolean;
    "theme": string;
    "fontFamily": string;
    "fontSize": number;
    "borderRadius": number;
    "navBarHeight": number;
    "paneHeaderHeight": number;

    /** Creates a new UIConfig instance. */
    constructor($$source: Partial<UIConfig> = {}) {
        if (!("animations" in $$source)) {
            this["animations"] = false;
        }
        if (!("theme" in $$source)) {
            this["theme"] = "";
        }
        if (!("fontFamily" in $$source)) {
            this["fontFamily"] = "";
        }
        if (!("fontSize" in $$source)) {
            this["fontSize"] = 0;
        }
        if (!("borderRadius" in $$source)) {
            this["borderRadius"] = 0;
        }
        if (!("navBarHeight" in $$source)) {
            this["navBarHeight"] = 0;
        }
        if (!("paneHeaderHeight" in $$source)) {
            this["paneHeaderHeight"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UIConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): UIConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UIConfig($$parsedSource as Partial<UIConfig>);
    }
}

// Private type creation functions
const $$createType0 = Bookmark.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = UIConfig.createFrom;
const $$createType3 = TerminalConfig.createFrom;
const $$createType4 = BrowserConfig.createFrom;
const $$createType5 = PanesConfig.createFrom;
const $$createType6 = PaneConfig.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = ShellOption.createFrom;
const $$createType9 = $Create.Array($$createType8);
