// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TerminalService manages pseudo-terminal sessions for the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * CloseTerminal kills the process, closes the PTY, and removes the session.
 */
export function CloseTerminal(id: string): $CancellablePromise<void> {
    return $Call.ByID(2233651159, id);
}

/**
 * CreateTerminal creates a new PTY session running the given shell.
 * If shell is empty, the default shell is detected from the environment.
 * Returns the session ID.
 */
export function CreateTerminal(shell: string): $CancellablePromise<string> {
    return $Call.ByID(1183800049, shell);
}

/**
 * ResizeTerminal resizes the PTY to the given columns and rows.
 */
export function ResizeTerminal(id: string, cols: number, rows: number): $CancellablePromise<void> {
    return $Call.ByID(3061528445, id, cols, rows);
}

/**
 * WriteTerminal writes base64-encoded input data to the PTY session.
 */
export function WriteTerminal(id: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(2145289508, id, data);
}
