// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WorkspaceService provides methods for managing the workspace pane layout.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetDefaultPanes returns the default workspace layout:
 * three terminal panes and one notes pane.
 */
export function GetDefaultPanes(): $CancellablePromise<$models.PaneConfig[]> {
    return $Call.ByID(91957092).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetPaneLayout returns the current pane layout configuration.
 * For now this returns the default set of panes.
 */
export function GetPaneLayout(): $CancellablePromise<$models.PaneConfig[]> {
    return $Call.ByID(951703140).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.PaneConfig.createFrom;
const $$createType1 = $Create.Array($$createType0);
