#!/usr/bin/env python3
"""Generate default Fly Dockerfiles from the single Rust image definition."""
import argparse
from pathlib import Path

root = Path(__file__).resolve().parents[3]
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
template = (root / 'deploy/fly/rust/Dockerfile').read_text()
ignore = (root / 'deploy/fly/rust/Dockerfile.dockerignore').read_text()
failed = []
for role in ('node', 'hub', 'combined'):
    text = template.replace('ARG WKS_ROLE=node', f'ARG WKS_ROLE={role}', 1)
    lines = text.splitlines(keepends=True)
    lines.insert(1, '# Generated by deploy/fly/rust/render-dockerfiles.py; edit deploy/fly/rust/Dockerfile.\n')
    for filename, content in [('Dockerfile', ''.join(lines)), ('Dockerfile.dockerignore', ignore)]:
        path = root / 'deploy/fly' / role / filename
        if args.check:
            if not path.exists() or path.read_text() != content:
                failed.append(str(path.relative_to(root)))
        else:
            path.write_text(content)
if failed:
    parser.error('stale generated deployment definitions: ' + ', '.join(failed))
