//! One renderer for live and retained messages; native actions stay in trusted UI.
use super::*;
use base64::Engine;
use std::collections::{BTreeMap, BTreeSet};
use std::time::{Duration, Instant};
use wks_native::{
    features::Request,
    model::Row,
    reading::Anchor,
    transcript::{self as content, AssistantBlock, CardAction, FileChange},
};

#[derive(Default)]
pub(super) struct ChatUi {
    pub restored: bool,
    pub open: BTreeMap<String, bool>,
    text_pages: BTreeMap<String, usize>,
    pub dismissed: BTreeMap<String, u64>,
    pub viewer: super::file_viewer::FileViewer,
    previews: BTreeMap<String, Preview>,
    pub wanted: BTreeSet<String>,
    preview_number: u64,
    preview_scheduled: bool,
    preview_inflight: bool,
    frozen: BTreeMap<String, Frozen>,
    capture_number: u64,
}
struct Preview {
    image: Option<Arc<gpui::Image>>,
    bytes: usize,
    at: Instant,
}
struct Frozen {
    files: Vec<FileChange>,
    estimated: bool,
}

fn turn_id(rows: &std::collections::VecDeque<Arc<Row>>, start: usize) -> String {
    serde_json::to_string(&Anchor::at(rows, start)).unwrap_or_default()
}
fn literal(id: String, text: &str, window: &mut Window, cx: &mut App) -> TextView {
    // HTML is generated by us, with all message text escaped. <pre> preserves
    // whitespace, asterisks, tags and fences verbatim; it never enables actions.
    let escaped = content::escape_native_html_text(text);
    TextView::html(
        SharedString::from(id),
        format!("<pre>{escaped}</pre>"),
        window,
        cx,
    )
    .selectable(true)
}
impl Workspace {
    /// Opening or switching to a conversation always lands on the latest message.
    pub(super) fn land_on_latest(&mut self) {
        if self.chat.restored || self.view.loading || self.view.transcript.rows.is_empty() {
            return;
        }
        self.follow = true;
        self.list.scroll_to(ListOffset {
            item_ix: self.view.transcript.rows.len(),
            offset_in_item: px(0.),
        });
        self.chat.restored = true;
    }
    pub(super) fn receive_chat_requests(&mut self, view: &View, cx: &mut Context<Self>) {
        if let Some(state) = view
            .requests
            .get("previews")
            .filter(|s| !s.loading && s.number > self.chat.preview_number)
        {
            self.chat.preview_number = state.number;
            self.chat.preview_inflight = false;
            if let Request::Previews { paths } = &state.request {
                for path in paths {
                    let value = &state.value[path];
                    let image = value["dataUrl"].as_str().and_then(|url| {
                        let (mime, data) = url.strip_prefix("data:")?.split_once(";base64,")?;
                        let format = gpui::ImageFormat::from_mime_type(mime)?;
                        if format == gpui::ImageFormat::Svg || data.len() > 3 * 1024 * 1024 {
                            return None;
                        }
                        let bytes = base64::engine::general_purpose::STANDARD
                            .decode(data)
                            .ok()?;
                        Some((
                            bytes.len(),
                            Arc::new(gpui::Image::from_bytes(format, bytes)),
                        ))
                    });
                    let (bytes, image) = image.map(|(b, i)| (b, Some(i))).unwrap_or((0, None));
                    self.chat.previews.insert(
                        path.clone(),
                        Preview {
                            image,
                            bytes,
                            at: Instant::now(),
                        },
                    );
                    self.chat.wanted.remove(path);
                }
                while self.chat.previews.len() > 32
                    || self.chat.previews.values().map(|p| p.bytes).sum::<usize>()
                        > 16 * 1024 * 1024
                {
                    let oldest = self
                        .chat
                        .previews
                        .iter()
                        .min_by_key(|(_, p)| p.at)
                        .map(|(k, _)| k.clone())
                        .unwrap();
                    self.chat.previews.remove(&oldest);
                }
            }
            // Invalidate heights after asynchronous thumbnail arrival.
            self.list.splice(
                0..self.view.transcript.rows.len(),
                self.view.transcript.rows.len(),
            );
        }
        if let Some(state) = view
            .requests
            .get("turn-changes")
            .filter(|s| !s.loading && s.number > self.chat.capture_number)
        {
            self.chat.capture_number = state.number;
            if let Request::TurnChanges { session, turn, cwd } = &state.request
                && let Some(frozen) = self.chat.frozen.get_mut(&format!("{session}\0{turn}"))
                && state.error.is_none()
            {
                let mut all_exact = true;
                for file in &mut frozen.files {
                    let relative = file
                        .path
                        .strip_prefix(&format!("{}/", cwd.trim_end_matches('/')))
                        .unwrap_or(&file.path);
                    let mut found = false;
                    let mut added = 0;
                    let mut removed = 0;
                    for mode in ["staged", "unstaged"] {
                        for entry in state.value[mode]["files"].as_array().into_iter().flatten() {
                            if entry["path"] == relative
                                && entry["added"].is_u64()
                                && entry["deleted"].is_u64()
                            {
                                added += entry["added"].as_u64().unwrap() as usize;
                                removed += entry["deleted"].as_u64().unwrap() as usize;
                                found = true;
                            }
                        }
                    }
                    if found {
                        file.added = added;
                        file.removed = removed;
                    } else {
                        all_exact = false;
                    }
                }
                frozen.estimated = !all_exact;
            }
        }
        // Freeze on the observed end of a live turn. Historical rows use clearly
        // labelled tool estimates, rather than querying today's repository state.
        if view.selected == self.view.selected
            && let Some(id) = &view.selected
        {
            let old = self.view.sessions.iter().find(|s| &s.id == id);
            let new = view.sessions.iter().find(|s| &s.id == id);
            if old.is_some_and(|s| {
                !matches!(
                    s.state.as_str(),
                    "idle" | "input" | "done" | "background" | "stopped"
                )
            }) && new.is_some_and(|s| {
                matches!(s.state.as_str(), "idle" | "input" | "done" | "background")
            }) {
                let rows = &view.transcript.rows;
                let start = rows
                    .iter()
                    .rposition(|r| r.role == "You")
                    .map_or(0, |i| i + 1);
                let files = content::turn_changes(rows.iter().skip(start).map(AsRef::as_ref));
                if !files.is_empty() {
                    let turn = turn_id(rows, start);
                    let key = format!("{id}\0{turn}");
                    if let std::collections::btree_map::Entry::Vacant(e) =
                        self.chat.frozen.entry(key)
                    {
                        e.insert(Frozen {
                            files,
                            estimated: true,
                        });
                        while self.chat.frozen.len() > 100
                            || self
                                .chat
                                .frozen
                                .values()
                                .flat_map(|f| &f.files)
                                .map(|f| f.path.len() + std::mem::size_of::<FileChange>())
                                .sum::<usize>()
                                > 4 * 1024 * 1024
                        {
                            let key = self.chat.frozen.keys().next().cloned().unwrap();
                            self.chat.frozen.remove(&key);
                        }
                        self.request(
                            Request::TurnChanges {
                                session: id.clone(),
                                turn,
                                cwd: new.unwrap().cwd.clone(),
                            },
                            cx,
                        );
                    }
                }
            }
        }
        self.schedule_previews(cx);
    }
    fn schedule_previews(&mut self, cx: &mut Context<Self>) {
        if self.chat.preview_inflight
            || self.chat.preview_scheduled
            || self.chat.wanted.is_empty()
            || self
                .view
                .requests
                .get("previews")
                .is_some_and(|s| s.loading)
            || !self.view.connected
        {
            return;
        }
        self.chat.preview_scheduled = true;
        let entity = cx.entity().downgrade();
        cx.defer(move |cx| {
            let _ = entity.update(cx, |this, _cx| {
                this.chat.preview_scheduled = false;
                if this
                    .view
                    .requests
                    .get("previews")
                    .is_some_and(|s| s.loading)
                {
                    return;
                }
                let paths = this.chat.wanted.iter().take(8).cloned().collect::<Vec<_>>();
                if !paths.is_empty() {
                    match this
                        .controller
                        .command(Command::Request(Request::Previews { paths }))
                    {
                        Ok(()) => this.chat.preview_inflight = true,
                        Err(error) => this.local_notice = error.to_string(),
                    }
                }
            });
        });
    }
    fn toggle_chat(&self, key: String, label: String, cx: &mut Context<Self>) -> Stateful<Div> {
        self.button(SharedString::from(format!("toggle-{key}")), label, true)
            .debug_selector(|| "chat-section-toggle".into())
            .on_click(cx.listener(move |this, _, _, cx| {
                if this.chat.open.len() > 2048 {
                    this.chat.open.clear();
                }
                this.pause_follow();
                let anchor = this.scroll_anchor();
                let value = this.chat.open.entry(key.clone()).or_insert(false);
                *value = !*value;
                this.list.splice(
                    0..this.view.transcript.rows.len(),
                    this.view.transcript.rows.len(),
                );
                this.list.scroll_to(anchor);
                cx.notify();
            }))
    }
    pub(super) fn render_chat_row(
        &mut self,
        ix: usize,
        window: &mut Window,
        cx: &mut Context<Self>,
    ) -> gpui::AnyElement {
        #[cfg(feature = "ui-tests")]
        self.rendered_rows.borrow_mut().insert(ix);
        let view = self.view.clone();
        let rows = &view.transcript.rows;
        let Some(row) = rows.get(ix) else {
            return div().into_any_element();
        };
        let group = wks_native::tool_preview::group_span(rows, ix, self.settings.merge_turn_tools);
        // Preserve raw list indices for bookmarks and selection. The final slot
        // owns the group, so the existing tail probe still tracks its painted end.
        if group.as_ref().is_some_and(|span| ix + 1 < span.end) {
            return div().w_full().h(px(0.)).into_any_element();
        }
        let session = self.view.selected.clone().unwrap_or_default();
        let mut body = div()
            .group("message")
            .w_full()
            .py_1()
            .when(ix + 1 == rows.len(), |d| {
                d.debug_selector(|| "chat-content-column".into())
            });
        if let Some(span) = group {
            body = body
                .child(self.render_work_card(span, window, cx))
                .child(self.timestamp_footer(None, row.timestamp_ms).px_3());
        } else {
            body = body.child(self.render_message(row, "live", false, window, cx));
        }
        if row.role != "You" && (ix + 1 == rows.len() || rows[ix + 1].role == "You") {
            let start = (0..=ix)
                .rev()
                .find(|i| rows[*i].role == "You")
                .map_or(0, |i| i + 1);
            let key = format!("{session}\0{}", turn_id(rows, start));
            let estimate = content::turn_changes(
                rows.iter()
                    .skip(start)
                    .take(ix - start + 1)
                    .map(AsRef::as_ref),
            );
            let frozen = self.chat.frozen.get(&key);
            let files = frozen.map_or(&estimate, |f| &f.files);
            if !files.is_empty() {
                let estimated = frozen.is_none_or(|f| f.estimated);
                let p = self.appearance.palette();
                body = body.child(
                    div()
                        .mt_2()
                        .py_3()
                        .border_t_1()
                        .border_color(rgb(p.border))
                        .child(
                            div()
                                .flex()
                                .flex_wrap()
                                .items_center()
                                .gap_3()
                                .child(
                                    div()
                                        .flex_1()
                                        .text_size(px(12.))
                                        .font_weight(FontWeight::MEDIUM)
                                        .child(format!(
                                            "{} file{} changed",
                                            files.len(),
                                            if files.len() == 1 { "" } else { "s" }
                                        )),
                                )
                                .child(div().text_size(px(12.)).text_color(rgb(p.success)).child(
                                    format!("+{}", files.iter().map(|f| f.added).sum::<usize>()),
                                ))
                                .child(div().text_size(px(12.)).text_color(rgb(p.error)).child(
                                    format!("−{}", files.iter().map(|f| f.removed).sum::<usize>()),
                                ))
                                .child(
                                    self.quiet_button(
                                        "turn-changes",
                                        "Changes",
                                        IconName::ArrowRight,
                                        self.view.connected,
                                    )
                                    .when(
                                        self.view.connected,
                                        |d| {
                                            d.on_click(cx.listener(|this, _, window, cx| {
                                                this.open_feature(Screen::Changes, window, cx)
                                            }))
                                        },
                                    ),
                                ),
                        )
                        .child(div().text_size(px(10.)).text_color(rgb(p.muted)).child(
                            if estimated {
                                "Estimated from tools"
                            } else {
                                "Captured at turn end"
                            },
                        ))
                        .children(files.iter().map(|f| {
                            div()
                                .text_size(px(12.))
                                .text_color(rgb(p.muted))
                                .child(format!("{}  +{} −{}", f.path, f.added, f.removed))
                        })),
                );
            }
        }
        let tail_probe = (ix + 1 == rows.len()).then(|| {
            let entity = cx.entity().downgrade();
            let session = session.clone();
            let row = row.clone();
            canvas(
                move |bounds, _, cx| {
                    cx.defer(move |cx| {
                        let _ = entity.update(cx, |this, cx| {
                            this.resume_at_visible_tail(&session, &row, bounds, cx)
                        });
                    });
                },
                |_, _, _, _| {},
            )
            .absolute()
            .top_0()
            .left_0()
            .size_full()
        });
        // Children with no spawning call in view, pinned where they started.
        if let Some(children) = self.child_ui.overview.get(&ix).cloned() {
            body = body.child(self.render_overview(&session, &children, window, cx));
        }
        let earlier = (ix == 0 && self.view.transcript.has_older).then(|| self.render_earlier(cx));
        // Virtual list items are placed directly at the viewport origin. Center
        // the column inside a full-width item rather than on the item itself.
        div()
            .w_full()
            .relative()
            .children(tail_probe)
            .when(ix + 1 == rows.len(), |d| {
                d.debug_selector(|| "last-transcript-row".into())
            })
            .child(chrome::chat_column().children(earlier).child(body))
            .into_any_element()
    }
    /// Top-of-chat pager. The list draws 250px past the viewport, so the first
    /// row renders just before the reader reaches it: that is the moment to
    /// fetch the next page, keeping the scroll anchored on the current row.
    fn render_earlier(&self, cx: &mut Context<Self>) -> Stateful<Div> {
        let p = self.appearance.palette();
        let loading = self.view.loading_older;
        if !loading && !self.view.loading && self.view.connected {
            let this = cx.entity().downgrade();
            cx.defer(move |cx| {
                let _ = this.update(cx, |this, cx| this.command(Command::LoadOlder, cx));
            });
        }
        div()
            .id("earlier-messages")
            .debug_selector(|| "earlier-messages".into())
            .py_3()
            .flex()
            .justify_center()
            .child(
                div()
                    .id("earlier-messages-pill")
                    .px_3()
                    .py_1()
                    .rounded_full()
                    .border_1()
                    .border_color(rgb(p.border))
                    .bg(rgb(p.surface))
                    .flex()
                    .items_center()
                    .gap_2()
                    .text_size(px(11.))
                    .text_color(rgb(p.muted))
                    .when(loading, |d| {
                        d.child(brand_spinner(11., p, "earlier-messages-loading"))
                            .child("Loading earlier messages…")
                    })
                    .when(!loading, |d| {
                        d.cursor_pointer()
                            .hover(move |s| s.text_color(rgb(p.text)).bg(rgb(p.selected)))
                            .child(Icon::new(IconName::ArrowUp).size(px(11.)))
                            .child("Earlier messages")
                            .on_click(
                                cx.listener(|this, _, _, cx| this.command(Command::LoadOlder, cx)),
                            )
                    }),
            )
    }

    pub(super) fn render_message(
        &mut self,
        row: &Row,
        namespace: &str,
        continued: bool,
        window: &mut Window,
        cx: &mut Context<Self>,
    ) -> Div {
        let duration = (namespace == "live")
            .then(|| self.duration_labels.get(&row.key).cloned())
            .flatten();
        let timestamp = row
            .timestamp_ms
            .or_else(|| row.timestamp.as_deref().and_then(timing::parse_timestamp));
        let mut footer = self.timestamp_footer(duration.map(Into::into), timestamp);
        if row.tool.is_none() && row.role == "Assistant" {
            // Hover-only copy lives on the metadata line so it reserves no row.
            let session = self.view.selected.clone().unwrap_or_default();
            let copy = row.copy_text();
            footer = div()
                .flex()
                .items_center()
                .justify_end()
                .gap_1()
                .child(
                    self.icon_button(
                        SharedString::from(format!("copy-{namespace}:{session}:{}", row.key)),
                        "Copy message",
                        IconName::Copy,
                        true,
                    )
                    .size(px(22.))
                    .opacity(0.)
                    .group_hover("message", |style| style.opacity(1.))
                    .on_click(move |_, _, cx| {
                        cx.write_to_clipboard(ClipboardItem::new_string(copy.clone()))
                    }),
                )
                .child(footer);
        }
        self.render_message_content(row, namespace, continued, window, cx)
            .child(footer)
    }

    /// Quiet, right-aligned metadata below a message or work card.
    fn timestamp_footer(&self, duration: Option<SharedString>, timestamp: Option<i64>) -> Div {
        div()
            .debug_selector(|| "message-timestamp-footer".into())
            .flex()
            .justify_end()
            .items_center()
            .gap_2()
            .text_size(px(11.))
            .text_color(rgb(self.appearance.palette().disabled))
            .children(duration)
            .when_some(timestamp, |d, timestamp| {
                d.child(timing::timestamp_label(
                    Some(timestamp),
                    timing::now_ms(),
                    self.settings.twelve_hour_clock,
                ))
            })
    }
    fn render_message_content(
        &mut self,
        row: &Row,
        namespace: &str,
        continued: bool,
        window: &mut Window,
        cx: &mut Context<Self>,
    ) -> Div {
        let p = self.appearance.palette();
        let session = self.view.selected.clone().unwrap_or_default();
        let key = format!("{namespace}:{session}:{}", row.key);
        let copy = row.copy_text();
        let mut body = div()
            .w_full()
            .px_3()
            .py_1()
            .flex()
            .flex_col()
            .gap_2()
            .when(row.tool.is_some(), |d| d.relative().px_0().py_1().gap_1())
            .when(row.role == "You", |d| {
                d.max_w(gpui::relative(0.85))
                    .ml_auto()
                    .bg(rgb(p.user))
                    .rounded(px(p.composer_radius))
                    .px_4()
                    .py_3()
            })
            .when(row.tool.is_none() && row.role != "Assistant", |d| {
                d.child(
                    div()
                        .flex()
                        .justify_between()
                        .text_size(px(11.))
                        .text_color(rgb(p.muted))
                        .child(
                            div()
                                .flex()
                                .items_center()
                                .gap_2()
                                .when(row.role != "Assistant" && row.tool.is_none(), |d| {
                                    d.child(row.role.clone())
                                }),
                        )
                        .child(
                            self.icon_button(
                                SharedString::from(format!("copy-{key}")),
                                "Copy message",
                                IconName::Copy,
                                true,
                            )
                            .size(px(24.))
                            .opacity(0.)
                            .group_hover("message", |style| style.opacity(1.))
                            .on_click(move |_, _, cx| {
                                cx.write_to_clipboard(ClipboardItem::new_string(copy.clone()))
                            }),
                        ),
                )
            })
            .when(row.truncated, |d| {
                d.child(
                    div()
                        .text_color(rgb(p.warning))
                        .child("Some content was clipped. Open History for retained text."),
                )
            });
        if let Some(tool) = &row.tool {
            let live = namespace == "live";
            let input = tool.value();
            // Orchestration detail; live cards hold it inside the card body.
            let mut lead: Vec<gpui::AnyElement> = Vec::new();
            let mut trail: Vec<gpui::AnyElement> = Vec::new();
            if tool.category() == "Skill" {
                let target = tool.target();
                if let Some(skill) = self
                    .selected_session()
                    .and_then(|s| s.skills.as_array())
                    .into_iter()
                    .flatten()
                    .find(|s| s["name"] == target)
                {
                    let description = skill["description"].as_str().unwrap_or("");
                    let origin = skill["origin"].as_str().unwrap_or("");
                    lead.push(
                        div()
                            .flex()
                            .flex_wrap()
                            .items_baseline()
                            .gap_2()
                            .child(div().text_color(rgb(p.prose)).child(description.to_owned()))
                            .when(!origin.is_empty(), |d| {
                                d.child(
                                    div()
                                        .text_size(px(11.))
                                        .text_color(rgb(p.disabled))
                                        .child(origin.to_owned()),
                                )
                            })
                            .into_any_element(),
                    );
                }
            }
            if matches!(tool.category(), "Subagent" | "Workflow") {
                let description = input["prompt"]
                    .as_str()
                    .or_else(|| input["message"].as_str())
                    .or_else(|| input["task"].as_str())
                    .or_else(|| input["description"].as_str())
                    .unwrap_or("");
                if !description.is_empty() && description != tool.target() {
                    // Long dispatch briefs stay a few lines tall until asked for.
                    let long = description.lines().count() > 6 || description.len() > 600;
                    let open_key = format!("{key}-task-open");
                    let open = self.chat.open.get(&open_key).copied().unwrap_or(false);
                    lead.push(
                        div()
                            .pl(px(10.))
                            .border_l_2()
                            .border_color(gpui::Hsla::from(rgb(p.accent)).opacity(0.45))
                            .text_color(rgb(p.prose))
                            .child(
                                div()
                                    .when(long && !open, |d| d.max_h(px(132.)).overflow_hidden())
                                    .child(literal(format!("{key}-task"), description, window, cx)),
                            )
                            .when(long, |d| {
                                d.child(
                                    div()
                                        .id(SharedString::from(format!("{open_key}-toggle")))
                                        .debug_selector(|| "task-brief-toggle".into())
                                        .mt_1()
                                        .text_size(px(11.))
                                        .text_color(rgb(p.accent))
                                        .cursor_pointer()
                                        .hover(|s| s.underline())
                                        .child(if open { "Show less" } else { "Show full task" })
                                        .on_click(cx.listener(move |this, _, _, cx| {
                                            this.toggle_open(open_key.clone(), false, cx)
                                        })),
                                )
                            })
                            .into_any_element(),
                    );
                }
            }
            if let Some(path) = input["file_path"]
                .as_str()
                .or_else(|| input["path"].as_str())
            {
                let cwd = self
                    .selected_session()
                    .map(|s| s.cwd.as_str())
                    .unwrap_or("");
                let link = super::file_viewer::tool_link(cwd, &input, path);
                trail.push(
                    self.file_button(&format!("{key}-file"), link, path, cx)
                        .into_any_element(),
                );
            }
            if live && let Some(children) = self.child_ui.agents.by_tool.get(&tool.id).cloned() {
                trail.push(
                    self.render_children(&session, &key, &children, window, cx)
                        .into_any_element(),
                );
            }
            if tool.category() == "Workflow" {
                let result =
                    serde_json::from_str::<serde_json::Value>(&tool.output).unwrap_or_default();
                let run_id = input["runId"]
                    .as_str()
                    .or_else(|| input["run_id"].as_str())
                    .or_else(|| result["runId"].as_str())
                    .or_else(|| result["run_id"].as_str());
                if let Some(run) = run_id.and_then(|id| {
                    self.selected_session()
                        .and_then(|s| s.workflows.as_array())
                        .into_iter()
                        .flatten()
                        .find(|w| w["runId"] == id)
                }) {
                    trail.push(
                        div()
                            .flex()
                            .items_center()
                            .gap_2()
                            .child(
                                div()
                                    .text_color(rgb(p.text))
                                    .font_weight(FontWeight::MEDIUM)
                                    .child(run["name"].as_str().unwrap_or("Workflow").to_owned()),
                            )
                            .child(run["status"].as_str().unwrap_or("").to_owned())
                            .into_any_element(),
                    );
                }
            }
            if live {
                lead.append(&mut trail);
                body = body.child(tools::card(
                    row,
                    &session,
                    self.tool_expansion.get(&tools::identity(row)).copied(),
                    cx.entity().downgrade(),
                    (p, self.settings.twelve_hour_clock),
                    lead,
                    window,
                    cx,
                ));
            } else {
                body = body
                    .child(format!(
                        "{} · {} · {}",
                        tool.category(),
                        wks_native::tool_preview::overview(&tool.name, &tool.input),
                        if tool.is_error {
                            "Failed"
                        } else if tool.complete {
                            "Completed"
                        } else {
                            "Awaiting result"
                        }
                    ))
                    .children(lead);
                let changes = tool.changes();
                for (n, file) in changes.iter().enumerate() {
                    body = body
                        .child(div().text_color(rgb(p.accent)).child(file.path.clone()))
                        .child(self.diff_lines(&format!("{key}-diff-{n}"), &file.diff, window, cx));
                }
                let details = format!("{key}-input");
                let expanded = self.chat.open.get(&details).copied().unwrap_or(false);
                body = body.child(self.toggle_chat(
                    details.clone(),
                    if expanded { "Hide input" } else { "Show input" }.into(),
                    cx,
                ));
                if expanded {
                    body = body.child(self.render_raw(
                        &details,
                        &if tool.clipped {
                            tool.input.clone()
                        } else {
                            serde_json::to_string_pretty(&tool.value())
                                .unwrap_or_else(|_| tool.input.clone())
                        },
                        window,
                        cx,
                    ));
                }
                if !tool.output.is_empty() {
                    body = body.child(self.render_raw(
                        &format!("{key}-output"),
                        &tool.output,
                        window,
                        cx,
                    ));
                }
                body = body.children(trail);
            }
            let tool_copy = row.copy_text();
            return body.child(
                div().absolute().top(px(9.)).right(px(8.)).child(
                    self.icon_button(
                        SharedString::from(format!("copy-{key}")),
                        "Copy message",
                        IconName::Copy,
                        true,
                    )
                    .size(px(24.))
                    .opacity(0.)
                    .group_hover("message", |style| style.opacity(1.))
                    .on_click(move |_, _, cx| {
                        cx.write_to_clipboard(ClipboardItem::new_string(tool_copy.clone()))
                    }),
                ),
            );
        }
        if row.role == "Plan"
            && let Ok(steps) = serde_json::from_str::<serde_json::Value>(&row.text)
            && let Some(steps) = steps.as_array()
        {
            return body.children(steps.iter().map(|step| {
                div()
                    .text_color(rgb(if step["status"] == "completed" {
                        p.success
                    } else {
                        p.text
                    }))
                    .child(format!(
                        "{} · {}",
                        step["status"].as_str().unwrap_or("pending"),
                        step["content"].as_str().unwrap_or("")
                    ))
            }));
        }
        if continued || !matches!(row.role.as_str(), "You" | "Assistant") {
            return body.child(literal(key, &row.text, window, cx));
        }
        if row.role == "You"
            && let Some(fleet) = content::fleet(&row.text)
        {
            body = body.child(div().font_weight(FontWeight::SEMIBOLD).child(fleet.title));
            for (entry_index, (label, id)) in fleet.entries.into_iter().enumerate() {
                body = body.child(literal(
                    format!("{key}-entry-{entry_index}"),
                    &fleet.summaries[entry_index],
                    window,
                    cx,
                ));
                let reply = format!("Re: session:{id} ({label}) — ");
                let exists = self.view.sessions.iter().any(|s| s.id == id);
                let target = id.clone();
                body = body.child(
                    div()
                        .flex()
                        .gap_2()
                        .child(
                            self.button(
                                SharedString::from(format!("{key}-worker-{id}")),
                                format!("Open {label}"),
                                exists,
                            )
                            .when(exists, |d| {
                                d.on_click(cx.listener(move |this, _, _, cx| {
                                    this.command(Command::Select(target.clone()), cx)
                                }))
                            }),
                        )
                        .child(
                            self.button(
                                SharedString::from(format!("{key}-reply-{id}")),
                                "Reply",
                                true,
                            )
                            .on_click(cx.listener(
                                move |this, _, window, cx| this.prefill(&reply, window, cx),
                            )),
                        ),
                );
            }
            for (i, (title, report)) in fleet.reports.iter().enumerate() {
                body = body.child(
                    div()
                        .p_3()
                        .bg(rgb(p.surface))
                        .rounded_md()
                        .child(title.clone())
                        .child(if title.starts_with("Structured result") {
                            self.render_result(
                                &format!("{key}-report-{i}"),
                                title,
                                report,
                                window,
                                cx,
                            )
                            .into_any_element()
                        } else {
                            self.render_raw(&format!("{key}-report-{i}"), report, window, cx)
                                .into_any_element()
                        }),
                );
            }
            let original = format!("{key}-original");
            let expanded = self.chat.open.get(&original).copied().unwrap_or(false);
            body = body.child(
                self.toggle_chat(
                    original.clone(),
                    if expanded {
                        "Hide original wake"
                    } else {
                        "Show original wake"
                    }
                    .into(),
                    cx,
                ),
            );
            if expanded {
                body = body.child(self.render_raw(&original, &fleet.text, window, cx));
            }
            return body;
        }
        let cwd = self
            .selected_session()
            .map(|s| s.cwd.clone())
            .unwrap_or_default();
        let paths = content::image_paths(&row.text, row.role == "You", &cwd);
        let mut text = row.text.clone();
        for (marker, path) in paths {
            if self
                .chat
                .previews
                .get(&path)
                .is_some_and(|p| p.at.elapsed() > Duration::from_secs(300))
            {
                self.chat.previews.remove(&path);
            }
            if let Some(preview) = self.chat.previews.get(&path) {
                if let Some(image) = &preview.image {
                    if !marker.is_empty() {
                        text = text.replace(&marker, "");
                    }
                    let link = wks_native::links::tool_file(&cwd, &path, None);
                    let owner = session.clone();
                    body = body.child(
                        div()
                            .id(SharedString::from(format!("{key}-image-{path}")))
                            .debug_selector(|| "chat-image-thumbnail".into())
                            .cursor_pointer()
                            .on_click(cx.listener(move |this, _, _, cx| {
                                this.open_link(&owner, link.clone(), cx)
                            }))
                            .child(
                                gpui::img(image.clone())
                                    .max_w(px(320.))
                                    .max_h(px(180.))
                                    .object_fit(gpui::ObjectFit::Contain),
                            )
                            .child(
                                div()
                                    .text_size(px(11.))
                                    .text_color(rgb(p.muted))
                                    .child(path),
                            ),
                    );
                }
            } else {
                self.chat.wanted.insert(path);
            }
        }
        self.schedule_previews(cx);
        if row.role == "You" {
            return body.child(literal(key, &text, window, cx));
        }
        for (n, block) in content::assistant_blocks(&text).into_iter().enumerate() {
            let block_key = format!("{key}-{n}");
            match block {
                AssistantBlock::Markdown(markdown) => {
                    body = body.child(self.render_markdown(&block_key, &markdown, window, cx))
                }
                AssistantBlock::Result(raw) => {
                    body = body.child(self.render_result(
                        &block_key,
                        "Structured result",
                        &raw,
                        window,
                        cx,
                    ));
                }
                AssistantBlock::Card(card) => {
                    let mut card_body = div()
                        .p_3()
                        .bg(rgb(p.surface))
                        .rounded_md()
                        .flex()
                        .flex_col()
                        .gap_2()
                        .child(card.title)
                        .child(literal(block_key.clone(), &card.fallback, window, cx));
                    if !card.body.trim().is_empty() {
                        // Card links take the same routes as Markdown links;
                        // the component never opens a scheme or image itself.
                        let selector = format!("html-card-{block_key}");
                        card_body = card_body.child(
                            div().debug_selector(move || selector).child(
                                TextView::html(
                                    SharedString::from(format!("{block_key}-body")),
                                    card.body,
                                    window,
                                    cx,
                                )
                                .style(gpui_component::text::TextViewStyle {
                                    on_link_click: Some(self.link_handler(cx)),
                                    ..Default::default()
                                })
                                .selectable(true),
                            ),
                        );
                    }
                    // Trusted actions sit in their own footer row, as on the
                    // desktop card: small outlined buttons that wrap, with an
                    // icon and a tooltip naming what the host will actually do.
                    let enabled = namespace != "child-history"
                        && self.selected_session().is_some_and(|s| !s.stopped())
                        && self.view.connected;
                    let actions = card
                        .actions
                        .into_iter()
                        .enumerate()
                        .map(|(i, action)| {
                            let owner = session.clone();
                            let (icon, effect) = match &action {
                                wks_native::transcript::CardAction::OpenWorker { .. } => (
                                    "lucide/user-round.svg",
                                    "Opens that agent's conversation.",
                                ),
                                wks_native::transcript::CardAction::ViewDiff { .. } => (
                                    "lucide/file-diff.svg",
                                    "Shows the file's changes inside this project.",
                                ),
                                wks_native::transcript::CardAction::FillComposer { .. } => (
                                    "lucide/message-square-plus.svg",
                                    "Puts this text in the composer for you to read and send. Nothing is sent.",
                                ),
                            };
                            let selector = format!("card-action-{block_key}-{i}");
                            chrome::interactive_control(
                                div().id(SharedString::from(format!("{block_key}-action-{i}"))),
                                p,
                                enabled,
                            )
                            .debug_selector(move || selector)
                            .flex()
                            .items_center()
                            .gap(px(6.))
                            .px_2()
                            .py_1()
                            .border_1()
                            .border_color(rgb(p.border))
                            .rounded(px(p.control_radius))
                            .text_size(px(12.))
                            .font_weight(FontWeight::MEDIUM)
                            .text_color(rgb(if enabled { p.text } else { p.disabled }))
                            .tooltip(move |window, cx| gpui_component::tooltip::Tooltip::new(effect).build(window, cx))
                            .child(
                                gpui::svg()
                                    .path(icon)
                                    .size(px(12.))
                                    .flex_shrink_0()
                                    .text_color(rgb(if enabled { p.muted } else { p.disabled })),
                            )
                            .child(action.label())
                            .when(enabled, |d| {
                                d.hover(|s| s.bg(rgb(p.selected))).on_click(cx.listener(
                                    move |this, _, window, cx| {
                                        this.card_action(&owner, &action, window, cx)
                                    },
                                ))
                            })
                        })
                        .collect::<Vec<_>>();
                    if !actions.is_empty() {
                        card_body = card_body.child(
                            div()
                                .flex()
                                .flex_wrap()
                                .items_center()
                                .gap(px(6.))
                                .pt_2()
                                .border_t_1()
                                .border_color(rgb(p.border))
                                .children(actions),
                        );
                    }
                    body = body.child(card_body);
                }
            }
        }
        body
    }

    /// A tool's file target, opened through the same routing as chat links.
    pub(super) fn file_button(
        &self,
        key: &str,
        link: wks_native::links::Link,
        label: &str,
        cx: &mut Context<Self>,
    ) -> Stateful<Div> {
        let owner = self.view.selected.clone().unwrap_or_default();
        let p = self.appearance.palette();
        let label = match &link {
            wks_native::links::Link::File(target) => target.path.clone(),
            _ => label.to_owned(),
        };
        let image = matches!(
            &link,
            wks_native::links::Link::File(t) if t.kind == wks_native::links::FileKind::Image
        );
        chrome::interactive_control(
            div().id(SharedString::from(key.to_owned())),
            p,
            self.view.connected,
        )
        .rounded(px(p.control_radius))
        .min_w_0()
        .max_w_full()
        .flex()
        .items_center()
        .gap_2()
        .py_1()
        .text_size(px(11.))
        .text_color(rgb(if self.view.connected {
            p.muted
        } else {
            p.disabled
        }))
        .child(
            Icon::new(if image {
                IconName::GalleryVerticalEnd
            } else {
                IconName::File
            })
            .size(px(12.))
            .flex_shrink_0(),
        )
        .child(div().min_w_0().truncate().child(label))
        .when(self.view.connected, |d| {
            d.cursor_pointer()
                .hover_text_style(|s| s.text_color(rgb(p.accent)))
                .on_click(cx.listener(move |this, _, _, cx| {
                    cx.stop_propagation();
                    this.open_link(&owner, link.clone(), cx);
                }))
        })
    }
    fn render_raw(
        &self,
        key: &str,
        text: &str,
        window: &mut Window,
        cx: &mut Context<Self>,
    ) -> Div {
        let pages = text.len().div_ceil(32768).max(1);
        let page = self
            .chat
            .text_pages
            .get(key)
            .copied()
            .unwrap_or(0)
            .min(pages - 1);
        let mut start = page * 32768;
        while !text.is_char_boundary(start) {
            start -= 1;
        }
        let mut end = ((page + 1) * 32768).min(text.len());
        while !text.is_char_boundary(end) {
            end -= 1;
        }
        let prev_key = key.to_owned();
        let next_key = key.to_owned();
        div()
            .when(pages > 1, |d| {
                d.child(
                    div()
                        .flex()
                        .items_center()
                        .gap_2()
                        .child(
                            self.button(
                                SharedString::from(format!("{key}-prev")),
                                "Previous text",
                                page > 0,
                            )
                            .when(page > 0, |d| {
                                d.on_click(cx.listener(move |this, _, _, cx| {
                                    if this.chat.text_pages.len() > 512 {
                                        this.chat.text_pages.clear();
                                    }
                                    this.chat.text_pages.insert(prev_key.clone(), page - 1);
                                    cx.notify();
                                }))
                            }),
                        )
                        .child(format!("Part {} of {}", page + 1, pages))
                        .child(
                            self.button(
                                SharedString::from(format!("{key}-next")),
                                "Next text",
                                page + 1 < pages,
                            )
                            .when(page + 1 < pages, |d| {
                                d.on_click(cx.listener(move |this, _, _, cx| {
                                    if this.chat.text_pages.len() > 512 {
                                        this.chat.text_pages.clear();
                                    }
                                    this.chat.text_pages.insert(next_key.clone(), page + 1);
                                    cx.notify();
                                }))
                            }),
                        ),
                )
            })
            .child(literal(
                format!("{key}-page-{page}"),
                &text[start..end],
                window,
                cx,
            ))
            .font_family(gpui_component::Theme::global(cx).mono_font_family.clone())
            .text_size(gpui_component::Theme::global(cx).mono_font_size)
    }
    fn diff_lines(
        &self,
        key: &str,
        text: &str,
        window: &mut Window,
        cx: &mut Context<Self>,
    ) -> Div {
        let p = self.appearance.palette();
        let copy = text.to_owned();
        let raw_key = format!("{key}-raw");
        let expanded = self.chat.open.get(&raw_key).copied().unwrap_or(false);
        div().child(div().flex().gap_2()
            .child(self.button(SharedString::from(format!("{key}-copy")),"Copy diff",true).on_click(move|_,_,cx|cx.write_to_clipboard(ClipboardItem::new_string(copy.clone()))))
            .child(self.toggle_chat(raw_key.clone(),if expanded {"Hide selectable diff"}else{"Show selectable diff"}.into(),cx)))
            .child(super::smooth_scroll::scroll_zone(div().id(SharedString::from(key.to_owned())).max_h(px(320.)).overflow_y_scroll().font_family(gpui_component::Theme::global(cx).mono_font_family.clone())
                .children(text.lines().take(1000).map(|line|div().text_color(rgb(if line.starts_with('+'){p.success}else if line.starts_with('-'){p.error}else{p.muted})).child(line.to_owned())))))
            .when(text.lines().count()>1000,|d|d.child("Showing the first 1,000 lines. Copy or open the selectable diff for all lines."))
            .when(expanded,|d|d.child(self.render_raw(&raw_key,text,window,cx)))
    }
    fn prefill(&mut self, text: &str, window: &mut Window, cx: &mut Context<Self>) {
        let draft = self.composer.read(cx).value().to_string();
        let value = if draft.is_empty() {
            text.into()
        } else {
            format!("{draft}\n{text}")
        };
        self.composer
            .update(cx, |input, cx| input.set_value(value, window, cx));
        self.screen = Screen::Conversation;
        self.composer.read(cx).focus_handle(cx).focus(window);
        cx.notify();
    }
    pub(super) fn card_action(
        &mut self,
        owner: &str,
        action: &CardAction,
        window: &mut Window,
        cx: &mut Context<Self>,
    ) {
        if self.view.selected.as_deref() != Some(owner)
            || !self.view.connected
            || self.selected_session().is_none_or(|s| s.stopped())
        {
            return;
        }
        match action {
            CardAction::FillComposer { text, .. } => self.prefill(text, window, cx),
            CardAction::OpenWorker { session_id, .. } => {
                if self
                    .view
                    .sessions
                    .iter()
                    .any(|s| s.id == *session_id && s.parent_session_id == owner && !s.stopped())
                {
                    self.command(Command::Select(session_id.clone()), cx);
                } else {
                    self.local_notice =
                        "That agent is not a live worker of this conversation.".into();
                }
            }
            CardAction::ViewDiff { path, .. } => self.request(
                Request::CardDiff {
                    session: owner.into(),
                    path: path.clone(),
                },
                cx,
            ),
        }
        cx.notify();
    }
    fn close_preview(
        &self,
        key: &'static str,
        number: u64,
        cx: &mut Context<Self>,
    ) -> Stateful<Div> {
        self.icon_button(
            SharedString::from(format!("close-{key}")),
            "Close preview",
            IconName::Close,
            true,
        )
        .on_click(cx.listener(move |this, _, _, cx| {
            this.chat.dismissed.insert(key.into(), number);
            cx.notify();
        }))
    }
    pub(super) fn render_pending(&self, window: &mut Window, cx: &mut Context<Self>) -> Div {
        let p = self.appearance.palette();
        let mut body = div()
            .w_full()
            .max_w(px(CHAT_WIDTH))
            .mx_auto()
            .flex()
            .flex_col()
            .gap_2();
        for pending in self
            .view
            .pending_messages
            .iter()
            .filter(|p| Some(&p.session) == self.view.selected.as_ref())
        {
            let status = if pending.queued {
                "Queued — sends when this turn ends"
            } else if pending.accepted {
                "Sent — awaiting transcript acknowledgement"
            } else {
                "Sending…"
            };
            body = body.child(
                div()
                    .p_3()
                    .bg(rgb(p.user))
                    .rounded_lg()
                    .child(div().text_color(rgb(p.muted)).child(status))
                    .child(literal(
                        format!("pending-{}", pending.number),
                        &pending.text,
                        window,
                        cx,
                    )),
            );
        }
        if let Some(state) = self
            .view
            .requests
            .get("card-diff")
            .filter(|s| self.chat.dismissed.get("card-diff") != Some(&s.number))
            && let Request::CardDiff { session, .. } = &state.request
            && Some(session) == self.view.selected.as_ref()
        {
            body = body.child(self.close_preview("card-diff", state.number, cx));
            if let Some(error) = &state.error {
                body = body.child(div().text_color(rgb(p.warning)).child(error.clone()));
            } else if state.loading {
                body = body.child("Loading diff…");
            } else {
                let before = state.value["before"].as_str().unwrap_or("");
                let after = state.value["after"].as_str().unwrap_or("");
                let diff = before
                    .lines()
                    .map(|l| format!("-{l}\n"))
                    .chain(after.lines().map(|l| format!("+{l}\n")))
                    .collect::<String>();
                body = body.child(self.diff_lines("response-card-diff", &diff, window, cx));
            }
        }
        body
    }
}
