import React, { useEffect, useState } from 'react';
import PluginInstallDialog from './PluginInstallDialog';

/** The public plugin catalog's machine-readable index, regenerated by
 *  build_index.py in the workspacer-plugins repo. */
const CATALOG_INDEX_URL =
  'https://raw.githubusercontent.com/DJTouchette/workspacer-plugins/main/index.json';

/** One entry of the catalog's index.json. */
interface CatalogEntry {
  id: string;
  name: string;
  dir: string;
  category: string;
  kind: 'webview' | 'sidecar' | string;
  icon?: string;
  description?: string;
  repo: string;
  /** `owner/repo` ref the installer accepts. */
  install: string;
  panes?: string[];
  capabilities?: string[];
  consumes?: string[];
  emits?: string[];
  settings?: string[];
}

const CATEGORY_LABELS: Record<string, string> = {
  dashboards: 'Dashboards',
  automation: 'Automation',
  reach: 'Reach',
};

interface PluginCatalogDialogProps {
  /** Ids of already-installed plugins, so catalog entries show as "Installed". */
  installedIds: string[];
  onClose: () => void;
  /** Called after a successful install so the host can refresh the plugin list. */
  onInstalled?: (pluginId: string) => void;
}

/**
 * Browse the public plugin catalog (workspacer-plugins on GitHub) and install
 * from it. The index carries names, blurbs, and declared permissions, but the
 * actual install goes through the normal two-step dialog — inspect the real
 * downloaded manifest, then consent — so the catalog is a shop window, not a
 * consent bypass.
 */
const PluginCatalogDialog: React.FC<PluginCatalogDialogProps> = ({
  installedIds,
  onClose,
  onInstalled,
}) => {
  const [entries, setEntries] = useState<CatalogEntry[] | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [installed, setInstalled] = useState<Set<string>>(() => new Set(installedIds));
  // The entry being installed; renders the standard install dialog on top.
  const [installing, setInstalling] = useState<CatalogEntry | null>(null);

  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if (e.key === 'Escape' && !installing) {
        e.preventDefault();
        onClose();
      }
    };
    window.addEventListener('keydown', handler, true);
    return () => window.removeEventListener('keydown', handler, true);
  }, [onClose, installing]);

  useEffect(() => {
    let live = true;
    fetch(CATALOG_INDEX_URL)
      .then((r) => {
        if (!r.ok) throw new Error(`HTTP ${r.status}`);
        return r.json();
      })
      .then((ix: { plugins?: CatalogEntry[] }) => {
        if (live) setEntries(Array.isArray(ix.plugins) ? ix.plugins : []);
      })
      .catch((e) => {
        if (live) {
          setEntries([]);
          setError(`Could not load the catalog (${String((e as Error)?.message ?? e)})`);
        }
      });
    return () => {
      live = false;
    };
  }, []);

  // Preserve the index's category order (it's already grouped and sorted).
  const categories: string[] = [];
  for (const e of entries ?? []) {
    if (!categories.includes(e.category)) categories.push(e.category);
  }

  return (
    <div
      onMouseDown={onClose}
      style={{
        position: 'fixed',
        inset: 0,
        zIndex: 20000,
        backgroundColor: 'var(--wks-overlay, rgba(0,0,0,0.5))',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
      }}
    >
      <div
        onMouseDown={(e) => e.stopPropagation()}
        style={{
          width: 620,
          maxWidth: '94vw',
          maxHeight: '84vh',
          display: 'flex',
          flexDirection: 'column',
          backgroundColor: 'var(--wks-glass-strong)',
          backdropFilter: 'blur(var(--wks-glass-blur)) saturate(170%)',
          WebkitBackdropFilter: 'blur(var(--wks-glass-blur)) saturate(170%)',
          border: '1px solid var(--wks-glass-border)',
          borderRadius: 'var(--wks-radius-lg)',
          padding: 20,
          boxShadow:
            '0 16px 48px var(--wks-glass-shadow), inset 0 0 0 1.5px var(--wks-glass-highlight)',
          fontFamily: 'inherit',
        }}
      >
        <div
          style={{
            fontSize: '0.9rem',
            fontWeight: 600,
            color: 'var(--wks-text-primary)',
            marginBottom: 4,
          }}
        >
          Plugin catalog
        </div>
        <div style={{ fontSize: '0.7rem', color: 'var(--wks-text-muted)', marginBottom: 14 }}>
          Install-ready plugins from the public catalog. Installing shows the plugin's manifest and
          permissions before anything runs.
        </div>

        {error && (
          <div
            style={{
              marginBottom: 10,
              fontSize: '0.7rem',
              color: 'var(--wks-danger, #e05555)',
              wordBreak: 'break-word',
            }}
          >
            {error}
          </div>
        )}

        <div
          style={{
            overflow: 'auto',
            display: 'flex',
            flexDirection: 'column',
            gap: 8,
            paddingRight: 2,
          }}
        >
          {entries === null && (
            <div
              style={{
                padding: 20,
                textAlign: 'center',
                color: 'var(--wks-text-faint)',
                fontSize: '0.75rem',
              }}
            >
              Loading…
            </div>
          )}
          {entries?.length === 0 && !error && (
            <div
              style={{
                padding: 20,
                textAlign: 'center',
                color: 'var(--wks-text-faint)',
                fontSize: '0.75rem',
              }}
            >
              The catalog is empty.
            </div>
          )}
          {categories.map((cat) => (
            <React.Fragment key={cat}>
              <div
                style={{
                  marginTop: 6,
                  fontSize: '0.66rem',
                  fontWeight: 700,
                  textTransform: 'uppercase',
                  letterSpacing: '0.05em',
                  color: 'var(--wks-text-muted)',
                }}
              >
                {CATEGORY_LABELS[cat] ?? cat}
              </div>
              {entries
                ?.filter((e) => e.category === cat)
                .map((e) => {
                  const isInstalled = installed.has(e.id);
                  const caps = e.capabilities ?? [];
                  return (
                    <div
                      key={e.id}
                      style={{
                        border: '1px solid var(--wks-border-subtle)',
                        borderRadius: 'var(--wks-radius-md)',
                        padding: '10px 12px',
                        background: 'var(--wks-bg-surface)',
                      }}
                    >
                      <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                        <div style={{ minWidth: 0, flex: 1 }}>
                          <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                            {e.icon && <span style={{ fontSize: '0.9rem' }}>{e.icon}</span>}
                            <span style={{ fontSize: '0.82rem', fontWeight: 600 }}>{e.name}</span>
                            <span
                              style={{
                                fontSize: '0.64rem',
                                color: 'var(--wks-text-faint)',
                                border: '1px solid var(--wks-border-subtle)',
                                borderRadius: 3,
                                padding: '1px 5px',
                              }}
                            >
                              {e.kind}
                            </span>
                          </div>
                          {e.description && (
                            <div
                              style={{
                                fontSize: '0.7rem',
                                color: 'var(--wks-text-muted)',
                                marginTop: 3,
                                lineHeight: 1.45,
                              }}
                            >
                              {e.description}
                            </div>
                          )}
                          <div
                            style={{
                              fontSize: '0.64rem',
                              color: 'var(--wks-text-faint)',
                              marginTop: 4,
                              display: 'flex',
                              gap: 12,
                              flexWrap: 'wrap',
                            }}
                          >
                            <span>{e.install}</span>
                            {caps.length > 0 && (
                              <span>
                                needs: {caps.slice(0, 4).join(', ')}
                                {caps.length > 4 ? ` +${caps.length - 4} more` : ''}
                              </span>
                            )}
                          </div>
                        </div>
                        <button
                          onClick={() => !isInstalled && setInstalling(e)}
                          disabled={isInstalled}
                          style={{
                            fontSize: '0.72rem',
                            fontFamily: 'inherit',
                            flexShrink: 0,
                            alignSelf: 'center',
                            cursor: isInstalled ? 'default' : 'pointer',
                            background: isInstalled ? 'transparent' : 'var(--wks-accent)',
                            color: isInstalled
                              ? 'var(--wks-text-faint)'
                              : 'var(--wks-text-on-accent, #fff)',
                            border: isInstalled ? '1px solid var(--wks-border-input)' : 'none',
                            borderRadius: 'var(--wks-radius-sm)',
                            padding: '5px 14px',
                            fontWeight: 600,
                          }}
                        >
                          {isInstalled ? 'Installed' : 'Install…'}
                        </button>
                      </div>
                    </div>
                  );
                })}
            </React.Fragment>
          ))}
        </div>

        <div
          style={{
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
            marginTop: 16,
          }}
        >
          <a
            href="https://github.com/DJTouchette/workspacer-plugins"
            target="_blank"
            rel="noreferrer"
            style={{ fontSize: '0.66rem', color: 'var(--wks-text-faint)' }}
          >
            github.com/DJTouchette/workspacer-plugins
          </a>
          <button
            onClick={onClose}
            style={{
              fontSize: '0.78rem',
              fontFamily: 'inherit',
              cursor: 'pointer',
              background: 'transparent',
              color: 'var(--wks-text-tertiary)',
              border: '1px solid var(--wks-border-input)',
              borderRadius: 4,
              padding: '6px 14px',
            }}
          >
            Done
          </button>
        </div>
      </div>

      {installing && (
        // Keep the nested dialog's backdrop clicks from bubbling into this
        // overlay's onMouseDown (which would close the catalog too).
        <div onMouseDown={(e) => e.stopPropagation()}>
          <PluginInstallDialog
            initialUrl={installing.install}
            onClose={() => setInstalling(null)}
            onInstalled={(pluginId) => {
              setInstalled((prev) => new Set(prev).add(pluginId || installing.id));
              onInstalled?.(pluginId || installing.id);
              setInstalling(null);
            }}
          />
        </div>
      )}
    </div>
  );
};

export default PluginCatalogDialog;
