import React, { useEffect, useMemo, useState } from 'react';
import PluginInstallDialog from './PluginInstallDialog';

/** The public plugin catalog's machine-readable index, regenerated by
 *  build_index.py in the workspacer-plugins repo. */
const CATALOG_INDEX_URL =
  'https://raw.githubusercontent.com/DJTouchette/workspacer-plugins/main/index.json';

/** One entry of the catalog's index.json. */
interface CatalogEntry {
  id: string;
  name: string;
  dir: string;
  category: string;
  kind: 'webview' | 'sidecar' | string;
  icon?: string;
  description?: string;
  repo: string;
  /** `owner/repo` ref the installer accepts. */
  install: string;
  panes?: string[];
  capabilities?: string[];
  consumes?: string[];
  emits?: string[];
  settings?: string[];
}

const CATEGORY_LABELS: Record<string, string> = {
  dashboards: 'Dashboards',
  workbench: 'Workbench',
  automation: 'Automation',
  reach: 'Reach',
};

/** Icon-tile gradient per category — a stable visual family per shelf. */
const CATEGORY_TINT: Record<string, string> = {
  dashboards: 'linear-gradient(135deg, rgba(57,135,229,0.28), rgba(57,135,229,0.08))',
  workbench: 'linear-gradient(135deg, rgba(25,158,112,0.28), rgba(25,158,112,0.08))',
  automation: 'linear-gradient(135deg, rgba(144,133,233,0.28), rgba(144,133,233,0.08))',
  reach: 'linear-gradient(135deg, rgba(217,89,38,0.26), rgba(217,89,38,0.08))',
};

const KIND_META: Record<string, { label: string; hint: string }> = {
  webview: { label: 'pane', hint: 'Adds a pane — runs only while open' },
  sidecar: { label: 'background', hint: 'Runs a supervised background process' },
};

interface PluginCatalogDialogProps {
  /** Ids of already-installed plugins, so catalog entries show as "Installed". */
  installedIds: string[];
  onClose: () => void;
  /** Called after a successful install so the host can refresh the plugin list. */
  onInstalled?: (pluginId: string) => void;
}

/**
 * The plugin marketplace — browse the public catalog (workspacer-plugins on
 * GitHub) and install from it. The index carries names, blurbs, and declared
 * permissions, but the actual install goes through the normal two-step dialog
 * — inspect the real downloaded manifest, then consent — so the catalog is a
 * shop window, not a consent bypass.
 */
const PluginCatalogDialog: React.FC<PluginCatalogDialogProps> = ({
  installedIds,
  onClose,
  onInstalled,
}) => {
  const [entries, setEntries] = useState<CatalogEntry[] | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [installed, setInstalled] = useState<Set<string>>(() => new Set(installedIds));
  const [query, setQuery] = useState('');
  const [category, setCategory] = useState<string>('all');
  // The entry being installed; renders the standard install dialog on top.
  const [installing, setInstalling] = useState<CatalogEntry | null>(null);

  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if (e.key === 'Escape' && !installing) {
        e.preventDefault();
        onClose();
      }
    };
    window.addEventListener('keydown', handler, true);
    return () => window.removeEventListener('keydown', handler, true);
  }, [onClose, installing]);

  useEffect(() => {
    let live = true;
    fetch(CATALOG_INDEX_URL)
      .then((r) => {
        if (!r.ok) throw new Error(`HTTP ${r.status}`);
        return r.json();
      })
      .then((ix: { plugins?: CatalogEntry[] }) => {
        if (live) setEntries(Array.isArray(ix.plugins) ? ix.plugins : []);
      })
      .catch((e) => {
        if (live) {
          setEntries([]);
          setError(`Could not load the catalog (${String((e as Error)?.message ?? e)})`);
        }
      });
    return () => {
      live = false;
    };
  }, []);

  // Preserve the index's category order (it's already grouped and sorted).
  const categories = useMemo(() => {
    const out: string[] = [];
    for (const e of entries ?? []) if (!out.includes(e.category)) out.push(e.category);
    return out;
  }, [entries]);

  const visible = useMemo(() => {
    const q = query.trim().toLowerCase();
    return (entries ?? []).filter(
      (e) =>
        (category === 'all' || e.category === category) &&
        (!q ||
          e.name.toLowerCase().includes(q) ||
          (e.description ?? '').toLowerCase().includes(q) ||
          (e.capabilities ?? []).some((c) => c.toLowerCase().includes(q))),
    );
  }, [entries, query, category]);

  const installedCount = (entries ?? []).filter((e) => installed.has(e.id)).length;

  const chip = (value: string, label: string) => (
    <button
      key={value}
      onClick={() => setCategory(value)}
      style={{
        fontSize: '0.7rem',
        fontFamily: 'inherit',
        fontWeight: 600,
        cursor: 'pointer',
        padding: '3px 12px',
        borderRadius: 'var(--wks-radius-pill, 999px)',
        border: 'none',
        background: category === value ? 'var(--wks-accent)' : 'transparent',
        color: category === value ? 'var(--wks-text-on-accent, #fff)' : 'var(--wks-text-muted)',
      }}
    >
      {label}
    </button>
  );

  return (
    <div
      onMouseDown={onClose}
      style={{
        position: 'fixed',
        inset: 0,
        zIndex: 20000,
        backgroundColor: 'var(--wks-overlay, rgba(0,0,0,0.5))',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
      }}
    >
      <div
        onMouseDown={(e) => e.stopPropagation()}
        style={{
          width: 880,
          maxWidth: '94vw',
          height: '84vh',
          display: 'flex',
          flexDirection: 'column',
          backgroundColor: 'var(--wks-glass-strong)',
          backdropFilter: 'blur(var(--wks-glass-blur)) saturate(170%)',
          WebkitBackdropFilter: 'blur(var(--wks-glass-blur)) saturate(170%)',
          border: '1px solid var(--wks-glass-border)',
          borderRadius: 'var(--wks-radius-lg)',
          overflow: 'hidden',
          boxShadow:
            '0 16px 48px var(--wks-glass-shadow), inset 0 0 0 1.5px var(--wks-glass-highlight)',
          fontFamily: 'inherit',
          position: 'relative',
        }}
      >
        {/* Soft accent glow behind the hero, like the spawn dialog. */}
        <div
          aria-hidden
          style={{
            position: 'absolute',
            top: '-30%',
            left: '50%',
            transform: 'translateX(-50%)',
            width: 620,
            height: 420,
            borderRadius: '50%',
            background:
              'radial-gradient(circle, color-mix(in srgb, var(--wks-accent) 10%, transparent) 0%, transparent 65%)',
            pointerEvents: 'none',
          }}
        />

        {/* ── Hero: title + search + shelves ── */}
        <div style={{ position: 'relative', padding: '22px 24px 12px', flexShrink: 0 }}>
          <div style={{ display: 'flex', alignItems: 'baseline', gap: 10 }}>
            <div
              style={{
                fontSize: '1.05rem',
                fontWeight: 700,
                letterSpacing: '-0.01em',
                color: 'var(--wks-text-primary)',
              }}
            >
              Plugin marketplace
            </div>
            <div style={{ fontSize: '0.7rem', color: 'var(--wks-text-faint)' }}>
              {entries ? `${entries.length} plugins · ${installedCount} installed` : ''}
            </div>
            <div style={{ flex: 1 }} />
            <a
              href="https://github.com/DJTouchette/workspacer-plugins"
              target="_blank"
              rel="noreferrer"
              style={{ fontSize: '0.68rem', color: 'var(--wks-text-faint)' }}
            >
              catalog on GitHub ↗
            </a>
          </div>
          <div style={{ fontSize: '0.72rem', color: 'var(--wks-text-muted)', marginTop: 3 }}>
            Every install shows the plugin's real manifest and permissions before anything runs.
          </div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginTop: 14 }}>
            <input
              autoFocus
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              placeholder="Search plugins, capabilities…"
              style={{
                flex: 1,
                minWidth: 0,
                padding: '8px 14px',
                fontSize: '0.78rem',
                fontFamily: 'inherit',
                backgroundColor: 'var(--wks-bg-input)',
                color: 'var(--wks-text-primary)',
                border: '1px solid var(--wks-border-input)',
                borderRadius: 'var(--wks-radius-pill, 999px)',
                outline: 'none',
              }}
            />
            <div
              style={{
                display: 'flex',
                gap: 2,
                padding: 2,
                borderRadius: 'var(--wks-radius-pill, 999px)',
                background: 'var(--wks-bg-raised)',
                border: '1px solid var(--wks-border-subtle)',
                flexShrink: 0,
              }}
            >
              {chip('all', 'All')}
              {categories.map((c) => chip(c, CATEGORY_LABELS[c] ?? c))}
            </div>
          </div>
          {error && (
            <div
              style={{
                marginTop: 10,
                fontSize: '0.7rem',
                color: 'var(--wks-danger, #e05555)',
                wordBreak: 'break-word',
              }}
            >
              {error}
            </div>
          )}
        </div>

        {/* ── Card grid ── */}
        <div style={{ position: 'relative', flex: 1, overflowY: 'auto', padding: '4px 24px 20px' }}>
          {entries === null && (
            <div
              style={{
                padding: 40,
                textAlign: 'center',
                color: 'var(--wks-text-faint)',
                fontSize: '0.75rem',
              }}
            >
              Loading the catalog…
            </div>
          )}
          {entries !== null && visible.length === 0 && !error && (
            <div
              style={{
                padding: 40,
                textAlign: 'center',
                color: 'var(--wks-text-faint)',
                fontSize: '0.75rem',
              }}
            >
              Nothing matches.
            </div>
          )}
          <div
            style={{
              display: 'grid',
              gridTemplateColumns: 'repeat(auto-fill, minmax(255px, 1fr))',
              gap: 12,
            }}
          >
            {visible.map((e) => {
              const isInstalled = installed.has(e.id);
              const caps = e.capabilities ?? [];
              const kind = KIND_META[e.kind] ?? { label: e.kind, hint: e.kind };
              return (
                <div
                  key={e.id}
                  className="wks-market-card"
                  style={{
                    display: 'flex',
                    flexDirection: 'column',
                    gap: 9,
                    padding: 14,
                    borderRadius: 'var(--wks-radius-md, 13px)',
                    background: 'var(--wks-bg-surface)',
                    border: '1px solid var(--wks-border-subtle)',
                    transition: 'transform 0.12s ease, border-color 0.12s, box-shadow 0.12s',
                  }}
                >
                  <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                    <div
                      style={{
                        width: 40,
                        height: 40,
                        borderRadius: 11,
                        flexShrink: 0,
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                        fontSize: '1.15rem',
                        background: CATEGORY_TINT[e.category] ?? 'var(--wks-bg-elevated)',
                        border: '1px solid var(--wks-border-subtle)',
                      }}
                    >
                      {e.icon || '🔌'}
                    </div>
                    <div style={{ minWidth: 0, flex: 1 }}>
                      <div
                        style={{
                          fontSize: '0.84rem',
                          fontWeight: 650,
                          color: 'var(--wks-text-primary)',
                          overflow: 'hidden',
                          textOverflow: 'ellipsis',
                          whiteSpace: 'nowrap',
                        }}
                      >
                        {e.name}
                      </div>
                      <div
                        title={kind.hint}
                        style={{
                          display: 'inline-flex',
                          marginTop: 2,
                          fontSize: '0.6rem',
                          fontWeight: 700,
                          letterSpacing: '0.05em',
                          textTransform: 'uppercase',
                          color: 'var(--wks-text-faint)',
                        }}
                      >
                        {CATEGORY_LABELS[e.category] ?? e.category} · {kind.label}
                      </div>
                    </div>
                  </div>

                  <div
                    style={{
                      fontSize: '0.72rem',
                      color: 'var(--wks-text-muted)',
                      lineHeight: 1.5,
                      flex: 1,
                      display: '-webkit-box',
                      WebkitLineClamp: 3,
                      WebkitBoxOrient: 'vertical',
                      overflow: 'hidden',
                    }}
                  >
                    {e.description || 'No description.'}
                  </div>

                  <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                    <span
                      title={caps.length ? `Declares: ${caps.join(', ')}` : 'No capabilities'}
                      style={{
                        fontSize: '0.64rem',
                        color: 'var(--wks-text-faint)',
                        border: '1px solid var(--wks-border-subtle)',
                        borderRadius: 'var(--wks-radius-pill, 999px)',
                        padding: '1px 8px',
                        whiteSpace: 'nowrap',
                      }}
                    >
                      {caps.length === 0
                        ? 'no permissions'
                        : `${caps.length} permission${caps.length === 1 ? '' : 's'}`}
                    </span>
                    <div style={{ flex: 1 }} />
                    <button
                      onClick={() => !isInstalled && setInstalling(e)}
                      disabled={isInstalled}
                      style={{
                        fontSize: '0.72rem',
                        fontFamily: 'inherit',
                        flexShrink: 0,
                        cursor: isInstalled ? 'default' : 'pointer',
                        background: isInstalled ? 'transparent' : 'var(--wks-accent)',
                        color: isInstalled
                          ? 'var(--wks-success, #4ade80)'
                          : 'var(--wks-text-on-accent, #fff)',
                        border: isInstalled
                          ? '1px solid color-mix(in srgb, var(--wks-success, #4ade80) 35%, transparent)'
                          : 'none',
                        borderRadius: 'var(--wks-radius-pill, 999px)',
                        padding: '4px 14px',
                        fontWeight: 650,
                      }}
                    >
                      {isInstalled ? '✓ Installed' : 'Install'}
                    </button>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </div>

      {/* Hover lift for cards — inline styles can't do :hover. */}
      <style>{`
        .wks-market-card:hover {
          transform: translateY(-2px);
          border-color: color-mix(in srgb, var(--wks-accent) 45%, var(--wks-border-subtle));
          box-shadow: 0 8px 24px rgba(0,0,0,0.25);
        }
      `}</style>

      {installing && (
        // Keep the nested dialog's backdrop clicks from bubbling into this
        // overlay's onMouseDown (which would close the catalog too).
        <div onMouseDown={(e) => e.stopPropagation()}>
          <PluginInstallDialog
            initialUrl={installing.install}
            onClose={() => setInstalling(null)}
            onInstalled={(pluginId) => {
              setInstalled((prev) => new Set(prev).add(pluginId || installing.id));
              onInstalled?.(pluginId || installing.id);
              setInstalling(null);
            }}
          />
        </div>
      )}
    </div>
  );
};

export default PluginCatalogDialog;
