// Generated by scripts/gen-desktop-services.mjs; edit contracts/desktop-service-methods.json.
const methods = {
  "ownerMethods": [
    "desktop.worktreeInfo",
    "desktop.worktreeCreate",
    "desktop.worktreeRemove",
    "desktop.pricingGetRates",
    "desktop.pricingSaveOverrides",
    "desktop.claudeProfilesAccounts",
    "desktop.claudeProfilesLoginStatus",
    "desktop.claudeProfilesAddAccount",
    "desktop.toolsStatus",
    "desktop.fleetReviewRead",
    "desktop.fleetReviewForget",
    "desktop.taskInspectorEdit",
    "desktop.taskInspectorOpen",
    "desktop.dispatchHistoryRead",
    "desktop.htmlCardReadDiff",
    "desktop.fleetWorkflowRequest",
    "desktop.managerRequestPrepare",
    "desktop.managerRequestSend",
    "desktop.loadBriefBoard",
    "desktop.moveBriefCard",
    "desktop.claudeProfilesAdd",
    "desktop.claudeProfilesUpdate",
    "desktop.claudeProfilesRemove",
    "desktop.saveConfig",
    "desktop.agentSuggestTitle",
    "desktop.providerReadiness",
    "desktop.agentRuntimeStatus",
    "desktop.keepWarmHeartbeats",
    "desktop.workflowAgentTranscript",
    "desktop.workflowAgentConversation",
    "desktop.installUiFont",
    "desktop.downloadProjectIcon",
    "desktop.managerReplacement",
    "desktop.sessionGrantReconcile",
    "desktop.readFileBytes",
    "desktop.filePickerList"
  ],
  "assetMethods": [
    "ui.fonts",
    "ui.asset"
  ]
} as const;
export default methods;
