/**
 * The host-built document a response card is rendered inside.
 *
 * The model supplies FRAGMENTS (`bodyHtml`, `css`). This module supplies the
 * document: the doctype, the charset, the Content-Security-Policy, the theme
 * tokens and the one nonced script. Concatenation order is the security
 * property — the CSP `<meta>` is emitted before any generated byte, so a card
 * cannot precede, reorder or remove its own policy. It can only append content
 * the policy already governs.
 *
 * Split out as a pure string function on purpose, the way `webviewGuard.ts`
 * splits its policy from its wiring: the policy is unit-testable with no DOM,
 * no iframe and no Electron, and the component below it is a thin call site.
 * What a pure test CANNOT prove is that Chromium enforces any of it — that is
 * what `tests/e2e/htmlCard.test.ts` is for, in a real browser.
 */
import { CARD_RUNTIME_JS } from './cardRuntime';
import { sanitizeCardCss, sanitizeCardHtml } from './sanitizeCardHtml';
import type { HtmlCardEnvelope } from '../../../../main/shared/htmlCard';

/**
 * The policy, in one string.
 *
 * - `default-src 'none'` is the egress boundary. A sandboxed frame WITHOUT
 *   `allow-same-origin` still gets to issue `fetch`/`XHR`/`new Image().src`/
 *   WebSocket by spec — the opaque origin only stops it READING the response,
 *   while the request (and any query string it smuggles) still leaves the
 *   machine. On this machine that would also reach the loopback daemons. So the
 *   sandbox attribute is not the network control; this is.
 * - `script-src 'nonce-…'` is what makes "generated markup cannot supply a
 *   runnable script" enforceable by the browser rather than by the sanitizer.
 *   A nonce is per-render and unguessable, and the only element carrying it is
 *   the host's own runtime.
 * - `style-src 'unsafe-inline'` allows the host `<style>` blocks and `style=`
 *   attributes. It buys nothing dangerous: CSS cannot execute here, and every
 *   fetching form (`url()`, `@import`, fonts, images) is refused by the
 *   `'none'` default it would fall back to.
 * - `img-src 'none'` blocks every image source, including data URLs.
 * - `form-action 'none'` and `base-uri 'none'` close the two navigations that
 *   do not need script.
 */
export function cardCsp(nonce: string): string {
  return [
    "default-src 'none'",
    "img-src 'none'",
    "style-src 'unsafe-inline'",
    `script-src 'nonce-${nonce}'`,
    "form-action 'none'",
    "base-uri 'none'",
    "frame-src 'none'",
    "child-src 'none'",
    "object-src 'none'",
    "connect-src 'none'",
    "font-src 'none'",
    "media-src 'none'",
    "worker-src 'none'",
    "manifest-src 'none'",
  ].join('; ');
}

/** The sandbox token list for the `<iframe>`. `allow-scripts` and nothing
 *  else: no `allow-same-origin` (so the document's origin is opaque and
 *  `parent.document`, `localStorage` and any credential are unreachable), no
 *  `allow-popups`, no `allow-top-navigation`, no `allow-forms`,
 *  no `allow-modals`, no `allow-downloads`. */
export const CARD_SANDBOX = 'allow-scripts';

const escapeText = (value: string): string =>
  value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

/** A 128-bit hex nonce from the platform CSPRNG. Regenerated per render, so a
 *  nonce observed in one card's document is worthless in the next. */
export function cardNonce(): string {
  const bytes = new Uint8Array(16);
  crypto.getRandomValues(bytes);
  return Array.from(bytes, (b) => b.toString(16).padStart(2, '0')).join('');
}

/**
 * The `--wks-*` custom properties currently applied to the app document.
 *
 * Read from `documentElement.style` (where `themes.applyTheme` writes them with
 * `setProperty`, which validates each value) rather than from config: it costs
 * no ConfigProvider, it follows a custom theme and a live theme switch without
 * a second registry lookup, and it works unchanged in the web build and in the
 * screenshot harness. Values are re-checked anyway — the same `{}<>;@\` /
 * `url()` predicate the plugin-webview theme bridge applies, because this also
 * builds a raw CSS string rather than calling setProperty.
 */
export function hostThemeVars(root?: HTMLElement): Record<string, string> {
  const el = root ?? (typeof document !== 'undefined' ? document.documentElement : null);
  const out: Record<string, string> = {};
  if (!el) return out;
  const style = el.style;
  for (let i = 0; i < style.length; i++) {
    const prop = style.item(i);
    if (!prop.startsWith('--wks-')) continue;
    const value = style.getPropertyValue(prop).trim();
    if (!value || /[{}<>;@\\]|\/\*|\*\//.test(value) || /(?:url|image|image-set)\s*\(/i.test(value))
      continue;
    out[prop] = value;
  }
  return out;
}

/** Base stylesheet: the theme tokens, a small reset, and readable defaults for
 *  the elements a card actually uses. Zero-specificity `:where()` so any rule
 *  the card writes itself wins — the same contract plugin webviews get. */
function baseCss(vars: Record<string, string>, light: boolean): string {
  const tokens = Object.entries(vars)
    .map(([prop, value]) => `  ${prop}: ${value};`)
    .join('\n');
  return `:root {
${tokens}
  color-scheme: ${light ? 'light' : 'dark'};
  --wks-card-fg: var(--wks-text-primary, ${light ? '#1c1c1e' : '#e6e6e6'});
  --wks-card-muted: var(--wks-text-secondary, ${light ? '#5a5a5f' : '#9a9aa2'});
  --wks-card-bg: transparent;
  --wks-card-line: var(--wks-border-subtle, ${light ? '#00000018' : '#ffffff1f'});
  --wks-card-accent: var(--wks-accent, #6aa9ff);
}
:where(html, body) {
  margin: 0;
  padding: 0;
  background: var(--wks-card-bg);
  color: var(--wks-card-fg);
  font-family: var(--wks-font-sans, system-ui, -apple-system, 'Segoe UI', sans-serif);
  font-size: 0.8rem;
  line-height: 1.55;
  overflow-wrap: anywhere;
}
:where(body) { padding: 10px 12px; }
:where(h1, h2, h3, h4) { margin: 0 0 6px; font-size: 1em; font-weight: 600; }
:where(p, ul, ol, table, pre, details) { margin: 0 0 8px; }
:where(ul, ol) { padding-left: 18px; }
:where(table) { border-collapse: collapse; width: 100%; }
:where(th, td) { text-align: left; padding: 3px 8px; border-bottom: 1px solid var(--wks-card-line); vertical-align: top; }
:where(th) { color: var(--wks-card-muted); font-weight: 600; }
:where(th[data-wks-sort]) { cursor: pointer; user-select: none; }
:where(th[data-wks-sort])::after { content: ' \\2195'; opacity: 0.35; }
:where(th[data-wks-sort-dir='asc'])::after { content: ' \\2191'; opacity: 0.9; }
:where(th[data-wks-sort-dir='desc'])::after { content: ' \\2193'; opacity: 0.9; }
:where(code, pre, samp, kbd) { font-family: var(--wks-font-mono, ui-monospace, monospace); font-size: 0.92em; }
:where(pre) { overflow-x: auto; padding: 8px; border-radius: 6px; background: var(--wks-bg-elevated, ${light ? '#00000008' : '#ffffff0d'}); }
:where(summary) { cursor: pointer; }
:where(a) { color: var(--wks-card-accent); }
:where(small, .muted) { color: var(--wks-card-muted); }
:where(input) {
  font: inherit; color: inherit; padding: 3px 7px; box-sizing: border-box;
  border: 1px solid var(--wks-card-line); border-radius: 5px; background: transparent;
}
:where(button) {
  font: inherit; color: inherit; padding: 2px 8px; cursor: pointer;
  border: 1px solid var(--wks-card-line); border-radius: 5px; background: transparent;
}
:where([hidden]) { display: none !important; }`;
}

export interface CardDocumentOptions {
  nonce: string;
  themeVars?: Record<string, string>;
  light?: boolean;
}

export interface CardDocument {
  srcDoc: string;
  /** What the sanitizer took out, so the chrome can say so instead of silently
   *  rendering less than the model wrote. */
  removed: string[];
}

/** Build the complete document for one card. */
export function buildCardDocument(
  card: HtmlCardEnvelope,
  options: CardDocumentOptions,
): CardDocument {
  const { html, removed } = sanitizeCardHtml(card.bodyHtml);
  const css = card.css ? sanitizeCardCss(card.css) : '';
  const vars = options.themeVars ?? {};
  const srcDoc = [
    '<!doctype html>',
    '<html lang="en">',
    '<head>',
    '<meta charset="utf-8">',
    `<meta http-equiv="Content-Security-Policy" content="${cardCsp(options.nonce)}">`,
    `<title>${escapeText(card.title)}</title>`,
    `<style>${baseCss(vars, options.light ?? false)}</style>`,
    css ? `<style>${css}</style>` : '',
    '</head>',
    '<body>',
    html,
    `<script nonce="${options.nonce}">${CARD_RUNTIME_JS}</script>`,
    '</body>',
    '</html>',
  ]
    .filter(Boolean)
    .join('\n');
  return { srcDoc, removed };
}
