/**
 * The document a card is rendered inside, as a pure string.
 *
 * These are POLICY tests: they assert the shell says the right thing, in the
 * right order. They cannot and do not prove that Chromium enforces any of it —
 * jsdom has no CSP engine and no real iframe sandbox. That proof lives in
 * `tests/e2e/htmlCard.test.ts`, against a real browser.
 */
import { describe, it, expect } from 'vitest';
import { buildCardDocument, cardCsp, cardNonce, hostThemeVars, CARD_SANDBOX } from './cardShell';
import type { HtmlCardEnvelope } from '../../../../main/shared/htmlCard';

const card = (over: Partial<HtmlCardEnvelope> = {}): HtmlCardEnvelope => ({
  v: 1,
  title: 'A card',
  bodyHtml: '<p>body</p>',
  fallback: 'plain words',
  actions: [],
  ...over,
});

describe('cardCsp', () => {
  it('denies by default and names every fetching directive explicitly', () => {
    const csp = cardCsp('abc');
    expect(csp).toContain("default-src 'none'");
    // connect-src is the one that matters most: a sandboxed opaque-origin
    // document may still ISSUE fetch/XHR/WebSocket by spec, which on this
    // machine reaches the loopback daemons.
    for (const directive of [
      "connect-src 'none'",
      "frame-src 'none'",
      "object-src 'none'",
      "form-action 'none'",
      "base-uri 'none'",
      "worker-src 'none'",
      "font-src 'none'",
      "media-src 'none'",
    ]) {
      expect(csp).toContain(directive);
    }
    expect(csp).toContain("script-src 'nonce-abc'");
    // 'unsafe-inline' must NOT appear for scripts — a nonce plus unsafe-inline
    // would make the nonce decorative.
    expect(csp).not.toMatch(/script-src[^;]*unsafe-inline/);
    expect(csp).toContain("img-src 'none'");
  });
});

describe('cardNonce', () => {
  it('is fresh per render', () => {
    const seen = new Set(Array.from({ length: 50 }, cardNonce));
    expect(seen.size).toBe(50);
    for (const n of seen) expect(n).toMatch(/^[0-9a-f]{32}$/);
  });
});

describe('buildCardDocument', () => {
  it('emits the CSP before any generated byte', () => {
    const { srcDoc } = buildCardDocument(card({ bodyHtml: '<p>x</p>' }), { nonce: 'n1' });
    const csp = srcDoc.indexOf('Content-Security-Policy');
    expect(csp).toBeGreaterThan(-1);
    expect(csp).toBeLessThan(srcDoc.indexOf('<p>x</p>'));
    expect(csp).toBeLessThan(srcDoc.indexOf('<body>'));
  });

  it('gives the nonce to exactly one script — the host runtime', () => {
    const { srcDoc } = buildCardDocument(
      card({ bodyHtml: '<script nonce="n1">alert(1)</script><p>x</p>' }),
      { nonce: 'n1' },
    );
    expect(srcDoc.match(/<script/g)?.length).toBe(1);
    expect(srcDoc).not.toContain('alert(1)');
    expect(srcDoc).toContain('nonce="n1"');
  });

  it('escapes the title into the document', () => {
    const { srcDoc } = buildCardDocument(card({ title: '</title><script>x</script>' }), {
      nonce: 'n',
    });
    expect(srcDoc).toContain('&lt;/title&gt;');
    expect(srcDoc.match(/<script/g)?.length).toBe(1);
  });

  it('passes the card stylesheet through the css sanitizer', () => {
    const { srcDoc } = buildCardDocument(
      card({ css: '@import url("https://evil.test/x.css"); .a{color:red}' }),
      { nonce: 'n' },
    );
    expect(srcDoc).toContain('@import');
    expect(srcDoc).toContain('evil.test');
    expect(srcDoc).toContain('.a{color:red}');
  });

  it('reports what the sanitizer removed', () => {
    const { removed } = buildCardDocument(card({ bodyHtml: '<iframe src="x"></iframe><p>y</p>' }), {
      nonce: 'n',
    });
    expect(removed).toContain('element');
  });

  it('inlines the host theme tokens it is given', () => {
    const { srcDoc } = buildCardDocument(card(), {
      nonce: 'n',
      themeVars: { '--wks-text-primary': '#ffeedd' },
      light: true,
    });
    expect(srcDoc).toContain('--wks-text-primary: #ffeedd;');
    expect(srcDoc).toContain('color-scheme: light');
  });
});

describe('hostThemeVars', () => {
  it('reads --wks-* off the element and drops anything that could break out or fetch', () => {
    const el = document.createElement('div');
    el.style.setProperty('--wks-good', '#123456');
    el.style.setProperty('--wks-shadow', '0 1px 2px rgba(0,0,0,0.4)');
    el.style.setProperty('--not-wks', '#000');
    // setProperty validates, so a breakout value has to be planted textually.
    el.setAttribute('style', `${el.getAttribute('style')};--wks-evil:url(https://evil.test/b.png)`);
    const vars = hostThemeVars(el);
    expect(vars['--wks-good']).toBe('#123456');
    expect(vars['--wks-shadow']).toBe('0 1px 2px rgba(0,0,0,0.4)');
    expect(vars['--not-wks']).toBeUndefined();
    expect(vars['--wks-evil']).toBeUndefined();
  });
});

describe('the sandbox attribute', () => {
  it('is allow-scripts and nothing else', () => {
    // Each omitted token is load-bearing: allow-same-origin would hand the card
    // parent.document and every credential; the rest would let it navigate,
    // pop up, submit or download.
    expect(CARD_SANDBOX).toBe('allow-scripts');
    for (const token of [
      'allow-same-origin',
      'allow-popups',
      'allow-top-navigation',
      'allow-forms',
      'allow-modals',
      'allow-downloads',
      'allow-pointer-lock',
    ]) {
      expect(CARD_SANDBOX).not.toContain(token);
    }
  });
});
